# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Kovan Test Network
chain = "kovan"
# Parity continously syncs the chain
mode = "active"
# Blockchain and settings will be stored in /home/.local/share/io.parity.ethereum.
base_path = "/home/.local/share/io.parity.ethereum"

[network]
# Parity will try to maintain connection to at least 50 peers.
min_peers = 50
# Parity will maintain at most 100 peers.
max_peers = 100
snapshot_peers = 25

[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Prune old state data. Maintains journal overlay - fast but extra 50MB of memory used.
pruning = "fast"
# If defined will never use more then 1024MB for all caches. (Overrides other cache settings).
cache_size = 1024

[snapshots]
# Enables multiple threads for snapshots creation.
processing_threads = 10

[misc]
# Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
logging = "rpc=debug"
# Logs will be stored at /home/kovan.log.
log_file = "/home/kovan.log"
